config/routes.rb
Rails.application.routes.draw do
  resources :users do  
    resources :serviceproviders
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/index'=>"serviceproviders#index",as:'all_providers'
  root to: 'users#new'
  get '/signin'=>"users#signin",as:'sign_in'
  post '/signin'=>"users#usersignin",as:'user_sign_in'
  delete "/sign_out" => "application#sign_out", as: "sign_out"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/serviceproviders/search' => 'serviceproviders#search', as: 'search_providers'
  get '/serviceproviders/:id' => 'serviceproviders#show', as: 'show_providers'

end

app/models/serviceprovider.rb
class Serviceprovider < ApplicationRecord
    belongs_to :user
    def self.search_providers(query)
        where("provider_name ILIKE :provider_name", provider_name: "%#{query}%")
    end
end

app/controllers/serviceproviders_controller.rb
class ServiceprovidersController < ApplicationController
  before_action :set_serviceprovider, only: [:show, :edit, :update, :destroy]

  # GET /serviceproviders
  # GET /serviceproviders.json
  def index
    @serviceproviders = Serviceprovider.all
  end

  # GET /serviceproviders/1
  # GET /serviceproviders/1.json
  def show
    @serviceprovider=Serviceprovider.find_by(id: params[:id])   
    @longitude= Serviceprovider.find_by(id: params[:id]).to_json

  end

  def search
    @companies = Serviceprovider.all
    @search_providers = Serviceprovider.search_providers(params["searchproviders"])
    @company= Serviceprovider.find_by(provider_name: params["searchproviders"])

        respond_to do |format|
            format.html { redirect_to show_providers_path(@company.id) }
            format.json { render json: @search_providers.map{|c| c.provider_name}}
        end
    end
  # GET /serviceproviders/new   
  def new
    @serviceprovider = Serviceprovider.new
  end

  # GET /serviceproviders/1/edit
  def edit
  end

  # POST /serviceproviders
  # POST /serviceproviders.json
  def create
    @serviceprovider = Serviceprovider.new(serviceprovider_params)
    @serviceprovider.user_id = current_user.id

    respond_to do |format|
      if @serviceprovider.save
        format.html { redirect_to user_path(current_user.id), notice: 'Serviceprovider was successfully created.' }
        format.json { render :show, status: :created, location: @serviceprovider }
      else
        format.html { render :new }
        format.json { render json: @serviceprovider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /serviceproviders/1
  # PATCH/PUT /serviceproviders/1.json
  def update
    respond_to do |format|
      if @serviceprovider.update(serviceprovider_params)
        format.html { redirect_to user_serviceprovider_path, notice: 'Serviceprovider was successfully updated.' }
        format.json { render :show, status: :ok, location: @serviceprovider }
      else
        format.html { render :edit }
        format.json { render json: @serviceprovider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /serviceproviders/1
  # DELETE /serviceproviders/1.json
  def destroy
    @serviceprovider.destroy
    respond_to do |format|
      format.html { redirect_to serviceproviders_url, notice: 'Serviceprovider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serviceprovider
      @serviceprovider = Serviceprovider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serviceprovider_params
      params.require(:serviceprovider).permit(:provider_name,:longitude,:price,:latitude,:email,:phone,:delivery,:collection,:description,:location,:materials)

    end
end      

app/helpers/serviceproviders_helper.rb
module ServiceprovidersHelper
end

app/views/serviceproviders/_form.html.erb
<%= form_with(model: serviceprovider, local: true) do |form| %>
  <% if serviceprovider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(serviceprovider.errors.count, "error") %> prohibited this serviceprovider from being saved:</h2>

      <ul>
      <% serviceprovider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/serviceproviders/edit.html.erb
<h1>Editing Serviceprovider</h1>
  <%= form_with( model: @serviceprovider,method: :put, local: true,url: user_serviceprovider_path) do |form| %>

 
  <% if @serviceprovider.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@serviceprovider.errors.count, "error") %> prohibited
        this listing from being saved:
      </h2>
      <ul>
        <% @serviceprovider.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :provider_name %>
    <%= form.text_field :provider_name %>

    <%= form.label :location %>
    <%= form.select :location, ['Johor Bahru', 'Kedah','Kelantan','Pahang','Melaka','Negeri Sembilan','Perak','Perlis','Pulau Pinang','Selangor','Terengganu','Sabah','Sarawak'], class:"col-8" %><p>
     
    Longitude of your company :<p> 
    <%= form.text_area :longitude, placeholder:'Longitude' %><p>
    
    Latitude of your company:<p>
    <%= form.text_area :latitude, placeholder:'Latitude' %><p>
     
    <%= form.label :description %>
    <%= form.text_area :description %>

    What type of materials do you print:
    <%= form.text_area :materials %>

    <%= form.label :phone %>
    <%= form.text_area :phone %>
    <%= form.label :email %>
    <%= form.text_area :email %>

    <%= form.label :delivery %>
    <%= form.select :delivery, ['Yes', 'No'], class:"col-8" %><p>

        
    <%= form.label :collection %>
    <%= form.select :collection, ['Yes', 'No'], class:"col-8" %><p>

    <%= form.submit %>
  </p>
 
<% end %>

app/views/serviceproviders/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1 class=''>3D Printing Service Providers</h1>
    <% @serviceproviders.each_with_index do |provider,index| %>
        <div class="card provider_all" style="width: 28rem;">
            <div class="card-body">
                <h5 class="card-title"><%=provider.provider_name%><br></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%=provider.location%><br></h6>
                <p class="card-text"> Description:
                <%=provider.description%><br>
                Phone:
                <%=provider.phone%><br>
                Email:
                <%=provider.email%><br>
                <%= link_to 'Show', user_serviceprovider_path(:user_id=>provider.user_id,:id=>provider.id)  %><br>

            </div>
        </div>
    <%end%>
</div>

app/views/serviceproviders/new.html.erb
<h1>New Serviceprovider</h1>



    <%= form_with( model: @serviceprovider,method: :post, local: true,url: user_serviceproviders_path) do |form| %>
          <%= form.text_field :provider_name, class:'col-8 form-control', placeholder:'Company Name' %><p>
          <%= form.text_field :description, class:'col-8 form-control', placeholder:'Description' %><p>
          <%= form.text_field :phone, class:'col-8 form-control', placeholder:'Phone Number' %><p>
          <%= form.text_field :email, class:'col-8 form-control', placeholder:'Email' %><p>
          Location:
          <%= form.select :location, ['Johor Bahru', 'Kedah','Kelantan','Pahang','Melaka','Negeri Sembilan','Perak','Perlis','Pulau Pinang','Selangor','Terengganu','Sabah','Sarawak'], class:"col-8" %><p>
          Longitude of your company:
          <%= form.text_field :longitude, class:'col-8 form-control', placeholder:'Longitude' %><p>
          Latitude of your company:
          <%= form.text_field :latitude, class:'col-8 form-control', placeholder:'Latitude' %><p>
          What type of materials do you print:
          <%= form.text_field :materials, class:'col-8 form-control', placeholder:'Materials' %><p>
          Price per g:
          <%= form.text_field :price, class:'col-8 form-control', placeholder:'Price' %><p>
            Do you provide self-collection service:
          <%= form.select :collection, ['Yes', 'No'], class:"col-8" %><p>
            Do you provide delivery service:
          <%= form.select :delivery, ['Yes', 'No'], class:"col-8" %><p>
          <%= form.submit 'Submit'%><p>
     <% end %>

app/views/serviceproviders/show.html.erb
<p id="notice"><%= notice %></p>
<meta name="viewport" content="initial-scale=1.0, width=device-width" />

<script src="http://js.api.here.com/v3/3.0/mapsjs-core.js"
  type="text/javascript" charset="utf-8"></script>
<script src="http://js.api.here.com/v3/3.0/mapsjs-service.js"
  type="text/javascript" charset="utf-8"></script>
<link href="https://fonts.googleapis.com/css?family=Anton|Bitter|Bungee|Patua+One" rel="stylesheet">

</div>
      <div class="row mb-2 comp_show">
        <div class="col-md-12">
          <div class="card flex-md-row mb-4 shadow-sm h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">3D Printing Service Company</strong>
              <h3 class="mb-2">
                <a class="text-dark comp_name" ><%= @serviceprovider.provider_name%></a>
              </h3>
              <div class="mb-5 text-muted comp_des"><%= @serviceprovider.description%></div>
              <p class="card-text comp_content mb-auto">Location:<%= @serviceprovider.location%></p>
              <p class="card-text comp_content mb-auto">Phone Number:<%= @serviceprovider.phone%></p>
              <p class="card-text comp_content mb-auto"> Email:<%= @serviceprovider.email%></p>
              <p class="card-text comp_content mb-auto"> Materials:<%= @serviceprovider.materials%></p>
              <p class="card-text comp_content mb-auto"> Price per gram:<%= @serviceprovider.price%></p> 
            </div>
            <div class="card-img-right flex-auto d-none d-lg-block"style="width: 50vw; height: 60vh" id="mapContainer"></div>
          </div>
        </div>
  <script>
  let data = JSON.parse('<%= raw @longitude %>')
  console.log(data)

    // Initialize the platform object:
    var platform = new H.service.Platform({
    'app_id': '<%= ENV['HERE_APP_ID']%>',
    'app_code': '<%= ENV['HERE_APP_SECRET']%>'
    });

    // Obtain the default map types from the platform object
    var maptypes = platform.createDefaultLayers();

    // Instantiate (and display) a map object:
    var map = new H.Map(
    document.getElementById('mapContainer'),
    maptypes.normal.map,
    {
      zoom: 18,
      center: { lng: data.longitude, lat: data.latitude}
    });
    var icon = new H.map.Icon("<%=asset_path ('MAKE1.png')%>", {size: {w: 42, h: 15}});
    var marker = new H.map.Marker({ 
      lat: data.latitude,
       lng: data.longitude 
       }, { 
      icon: icon 
      });
    map.addObject(marker);
   
  </script>