config/routes.rb
Rails.application.routes.draw do
  resources :users do  
    resources :serviceproviders
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/index'=>"serviceproviders#index",as:'all_providers'
  root to: 'users#new'
  get '/signin'=>"users#signin",as:'sign_in'
  post '/signin'=>"users#usersignin",as:'user_sign_in'
  delete "/sign_out" => "application#sign_out", as: "sign_out"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/serviceproviders/search' => 'serviceproviders#search', as: 'search_providers'
  get '/serviceproviders/:id' => 'serviceproviders#show', as: 'show_providers'

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/,presence: true
  validates :password_digest, presence:true
  validates :birthday, format:/([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))/
  has_secure_password
    has_many :authentications, dependent: :destroy
    has_many :serviceproviders, dependent:  :destroy
    mount_uploader :profilepicture, ImageUploader

    def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
        first_name: auth_hash["info"]["name"],
        email: auth_hash["info"]["email"],
        password: SecureRandom.hex(10)
      )
      user.authentications << authentication
      return user
    end
    def google_token
      x = self.authentications.find_by(provider: 'google_oauth2')
      return x.token unless x.nil?
    end
  
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  include BCrypt

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find_by(id: params[:id])
    
  end

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
  

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  # POST SIGN IN
  def usersignin
     # find the user
    user = User.find_by(email: params[:email])
  # authenticate user
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to user_path(current_user.id)
    else
      redirect_to root_url
    end

  end
  # GET USER SIGN IN PAGE
  def signin
  end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name,:profilepicture,:last_name,:gender,:email,:birthday,:password)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
   
   
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Anton|Bitter|Bungee|Patua+One" rel="stylesheet">

<div class="jumbotron welcome">
<div class="card-group">
  <div class="card_home card card-size">
       <img class ="picture col-12 " src='<%=asset_path ('IMG_7404.jpg')%>'>
  </div>
  <div class="card_home card">
    <div class="card-body">
      <h5 class="card-title ">  <div class='title_name'>MAKE ME3D</div> </h5>
        <p class="title_description">Find your reliable 3D printing service provider in nearby.</p>
        <p class="title_description">Print anything such as toys, tools or figure whenever you need it</p>
        <p class="title_description">It is much cheaper and faster to use 3D printing</p>
        <p class="title_description">Design your own 3D object and send to your 3D printing service provider </p>
        <p class="title_description">Feel more reliable by using our platform.</p>
        <p class="title_description"> If the quality of the 3D object is really bad, you can get a full refund </p>
    </div>
    <%if !logged_in?%>
     <div class="signup">
      <%= form_with(model: @user, local: true) do |form| %>
          <%= form.text_field :first_name, class:'col-11 form-control', placeholder:'First Name' %><br>
          <%= form.text_field :last_name, class:'col-11 form-control', placeholder:'Last Name' %><br>
          <%= form.text_field :email, class:'col-11 form-control', placeholder:'Email' %><br>
          <%= form.text_field :password, type:'password',class:'col-11 form-control', placeholder:'password' %><br>
          <%= form.select :gender,['Male', 'Female'],class:'col-11 form-control'%><br>
          <%= form.text_field :birthday, type: 'birthday',placeholder:'yyyy-mm-dd', class:"col-11 form-control"  %><br>
          <p> Profile Picture:
          <%= form.file_field :profilepicture %><br></p>
          <%= form.submit 'SIGN UP'%><br>
      <% end %>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class='container'>
<h2>Welcome back to ME3D</h2>
<%= image_tag(@users.profilepicture.url, alt: 'Image') if @users.profilepicture? %>
 <%if @users.gender=='Male'%>
  Mr. <%=@users.first_name%><br>
  <hr>   
  <%elsif @users.gender=='Female'%>
  Mrs.<%=@users.first_name%><br>
  <hr>
 <%end%>
 
 <%@users.birthday%>
    <%if @users.serviceprovider_ids!=[]%>
        <strong>Service Provider Information:</strong><p>
       
         
    <div class="row mb-2">
        <div class="col-md-8">
          <div class="card flex-md-row mb-4 shadow-sm h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">Your Company</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="#"><%= @users.serviceproviders.last.provider_name%><p></a>
              </h3>
              <div class="mb-1 text-muted"><%= @users.serviceproviders.last.description%><p></div>
              <p class="card-text mb-auto"> Phone Number :
                 <%= @users.serviceproviders.last.phone%><br>
                 Email:<%= @users.serviceproviders.last.email%><br>
                 States:<%= @users.serviceproviders.last.location%><br>
                 Delivery service:<%= @users.serviceproviders.last.delivery%><br>
                 Self collection service:<%= @users.serviceproviders.last.collection%></p>
            </div>
              <%if @users.serviceproviders.last.user_id==current_user.id%>
              <%= link_to 'Edit',edit_user_serviceprovider_path(@current_user) %> 
              <%end%>
          </div>
        </div>
 <%end%>
 </div>

app/views/users/signin.html.erb
  
<div class="card container signin_card ">
  <div class="card-body">
    <h5 class="card-title mb-5">SIGN IN</h5>
      <%= form_tag '/signin' do %>
        <div class='signin_tag'>
        <div class ='signin_title  col-10'> EMAIL
        <%= text_field_tag :email  %><br></div><br><br>
        <div class ='signin_title'> Password
        <%= password_field_tag :password %></div>
        </div><br><br>
        <button type="submit" class="btn btn-primary mr-3">Sign In</button>
        <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
      <% end %> 
      </div>
  </div>
</div>



  