config/routes.rb
Rails.application.routes.draw do
  resources :users do  
    resources :serviceproviders
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/index'=>"serviceproviders#index",as:'all_providers'
  root to: 'users#new'
  get '/signin'=>"users#signin",as:'sign_in'
  post '/signin'=>"users#usersignin",as:'user_sign_in'
  delete "/sign_out" => "application#sign_out", as: "sign_out"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  post '/serviceproviders/search' => 'serviceproviders#search', as: 'search_providers'
  get '/serviceproviders/:id' => 'serviceproviders#show', as: 'show_providers'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Printing3d</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar fullbar navbar-expand-lg navbar-light ">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

  <img class='logo'src='<%=asset_path ('MAKE1.png')%>'>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
  
      <li class="nav-item nav-left">
          <%= link_to t(".Home"), all_providers_path %>
      </li>
        <%if logged_in? %>
      <li class="nav-item active nav-left">
         <%=link_to t(".Profile"), user_path(current_user) %>
      </li>
    <% end %>
    </ul>
      <%if logged_in? %>
        <%if current_user.serviceproviders==[]%>
         <div class="nav-right">
          <%=link_to "Be a Service Provider", new_user_serviceprovider_path(current_user) %>
         <% end %>
         </div>
         <div class="nav-right">
          <%= link_to t(".sign_out"), sign_out_path, method: :delete, class:"nav-link" %>
          </div>
      <% else %>
          <%= link_to t(".sign_up"), root_url, class:"nav-link" %>
          <%= link_to t(".sign_in"), sign_in_path, class:"nav-link" %>
      <% end %>   
      </div>
      <%= form_with url: search_providers_path, local: true, class:'form-inline my-2 my-lg-0' , :method => 'post', id: "search-providers"  do |form| %>
      <%= form.text_field :searchproviders, class: "form-control mr-sm-2", list: 'list', id:"main-search", placeholder:"Search for a Company" %>
      <%= form.submit "Search", class:"btn btn-outline-primary my-2 my-sm-0" %>
      <datalist id="list"></datalist>
    <% end %>
  </div>
</nav>
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <script>
    $(document).on('turbolinks:load', function(){
    
    $("#search-providers").on("keyup", function(){
      autocomplete()
    });

    function autocomplete(){
      $.ajax({

        url: '/serviceproviders/search',
        type: 'POST',
        data: $("#search-providers").serialize(),
        dataType: 'json',
        error: function() {
            console.log("Something went wrong");
        },
        success: function(data) {
          document.getElementById('list').innerHTML = '';
          $("#list").empty();
          var uniquedata = [];
          $.each(data, function(i, el){
              if($.inArray(el, uniquedata) === -1) uniquedata.push(el);
          });
        
          uniquedata.forEach(function(element) {
            var option = document.createElement("option");
            option.value = element;

            //append option to list
            $("#list").append(option);
          });
        }
      });
    }
    })
    </script>
        <%= yield %>

  </body>

</html>